// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BitacoraAPP.Models
{
    public partial class MovimientosUsuario
    {
        public int Id { get; set; }
        public DateTime? HoraEntrada { get; set; }
        public DateTime? HoraSalida { get; set; }
        public int? EstadoUsuario { get; set; }
        public int? IdUsuario { get; set; }
        public int? CerrarRegistro { get; set; }

       
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}