// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BitacoraAPP.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            MovimientosUsuario = new HashSet<MovimientosUsuario>();
        }

        public int Id { get; set; }
        public string ClaveUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public int? TipoUsuario { get; set; }

        public virtual ICollection<MovimientosUsuario> MovimientosUsuario { get; set; }
    }
}